import type { FeatureCollection } from 'geojson';

/** Which layout a page uses. Mirrors the three legacy Nunjucks layouts. */
export type Layout = 'page' | 'custom' | 'bigmap';

/** Creative Commons attribution for a hero or card thumbnail. */
export interface Attribution {
	name: string;
	title: string;
	url: string;
	license: string;
}

/** A hero whose responsive derivatives are generated by `npm run images`. */
export interface Hero {
	type: 'autoImage';
	alt: string;
	desktop: string;
	mobile: string;
	attribution?: Attribution;
}

/** Card thumbnail generated from a single source photo by `npm run images`. */
export interface Thumb {
	type: 'generated';
	source: string;
	attribution?: Attribution;
}

/** Map configuration from front matter `geo`, with the legacy string numbers coerced. */
export interface Geo {
	lat?: number;
	lng?: number;
	zoom?: number;
	height?: string;
	bigMap?: boolean;
	colour?: string;
	geojsonUrl?: string;
	googleMaps?: string;
}

/** Front matter after parsing, coercion and validation. */
export interface Frontmatter {
	title: string;
	layout: Layout;
	description?: string;
	shortTitle?: string;
	tags: string[];
	related?: string;
	permalink?: string;
	icon?: string;
	hero?: Hero;
	thumb?: Thumb;
	geo?: Geo;
	geojson?: FeatureCollection;
	mapTitle?: string;
	mapDescription?: string;
	openDate?: string;
	country?: string;
	classNames?: string;
	showHeader: boolean;
	robots?: string;
	governingLaw?: string;
	date?: string;
	excludeFromCollections: boolean;
}

/** A parsed content file: front matter, raw body, and where it lives. */
export interface ContentFile {
	/** Content-relative file path, e.g. `brisbane-city/riverwalk/index.md`. */
	file: string;
	/** Content-relative directory, used to resolve page-relative asset paths. */
	directory: string;
	/** Site URL, e.g. `/brisbane-city/riverwalk/`. */
	url: string;
	frontmatter: Frontmatter;
	body: string;
}

/** One `<source>` element of a hand-written responsive hero. */
export interface SourceDescriptor {
	srcset: string;
	type?: string;
	media?: string;
	sizes?: string;
	width?: number;
	height?: number;
}


/* ------------------------------------------------------------------ *
 * View models — the shapes the Svelte components receive. Defined here
 * rather than beside the server code that builds them so that components
 * can import them without reaching into `$lib/server`.
 * ------------------------------------------------------------------ */

/** A hero resolved to concrete `<picture>` markup inputs. */
export interface HeroModel {
	sources: SourceDescriptor[];
	src: string;
	alt: string;
	width?: number;
	height?: number;
	attribution?: Attribution;
}

/** A card thumbnail resolved to concrete markup inputs. */
export interface CardThumb {
	sources: SourceDescriptor[];
	src: string;
	width?: number;
	height?: number;
}

/** Everything a card in a `related` grid needs to render. */
export interface CardSummary {
	url: string;
	title: string;
	description?: string;
	icon?: string;
	thumb?: CardThumb;
	attribution?: Attribution;
}

/** A badge shown in a page's infobox, driven by front matter `tags`. */
export interface Facet {
	tag: string;
	colour: string;
	iconUrl: string;
	title: string;
	/** Name of the source icon, credited in the hover tooltip. */
	iconName: string;
	/** Noun Project contributor, credited in the hover tooltip. */
	contributor: string;
	body: string;
}

/** Everything the map needs, with inline GeoJSON already lifted out to its own file. */
export interface MapConfig {
	/** Starting centre as `[lng, lat]`, when the page pins one. */
	centre?: [number, number];
	zoom?: number;
	height?: string;
	bigMap: boolean;
	colour?: string;
	geojsonUrl?: string;
	googleMaps?: string;
	title: string;
	description?: string;
}

/** A page as it appears in a footer or menu list. */
export interface NavItem {
	url: string;
	title: string;
	/** `shortTitle` where one exists, since the nav lists are tight on space. */
	shortName: string;
}

/** The page payload returned by the catch-all route's load function. */
export interface PageModel {
	url: string;
	title: string;
	description: string;
	layout: Layout;
	classNames?: string;
	showHeader: boolean;
	hero?: HeroModel;
	facets: Facet[];
	openDate?: string;
	/** Rendered HTML, split at each `{% ad %}` so ad components can sit between the pieces. */
	htmlSegments: string[];
	map?: MapConfig;
	relatedCollection?: string;
	country?: string;
	editUrl: string;
	icbm?: string;
}

/** Site-wide navigation and card data, shared by every page. */
export interface SiteData {
	/** Year the site was built, used for the footer copyright notice. */
	buildYear: number;
	menu: NavItem[];
	footer: Record<'brisbane' | 'day-trips' | 'moreton-bay' | 'rules' | 'legal', NavItem[]>;
	cards: Record<string, CardSummary[]>;
}
